apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: payment-api-key-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: payment-api-key
        property: api_key
